# qemu config file

# boot
# qemu-system-x86_64 -nodefaults -cpu host -display none -readconfig veos.ini -daemonize

[object]
  qom-type = "iothread"
  id = "iothread0"

[device]
  driver = "virtio-blk-pci"
  id = "virtblk0"
  drive = "drive0"
  packed = "on"
  iothread = "iothread0"
  num-queues = "2"

[drive]
  file = "vEOS64-lab-4.34.1F.qcow2"
  id = "drive0"
  if = "none"
  format = "qcow2"
  discard = "unmap"
  aio = "native"
  cache = "none"

[device]
  driver = "virtio-scsi-pci"
  id = "scsi"

[device]
  driver = "scsi-cd"
  drive = "cdrom0"

[drive]
  file = "Aboot-veos-serial-8.0.2.iso"
  format = "raw"
  if = "none"
  id = "cdrom0"

[chardev]
  backend = "pty"
  id = "pty0"
  mux = "on"
  nodelay = "on"
  server = "on"
  wait = "on"

[device]
  driver = "pci-serial"
  id = "ser0"
  chardev = "pty0"

[mon]
  mode = "readline"
  id = "mon0"
  chardev = "pty0"

[nic]
  id = "Ma1"
  type = "tap"
  ifname = "tap0"
  model = "virtio-net-pci"
  script = "no"
  downscript = "no"
  mac = "52:54:00:12:34:56"

[nic]
  id = "Et1"
  type = "socket"
  model = "virtio-net-pci"
  mac = "52:54:00:12:34:57"
  mcast = "230.0.0.1:3000"

[nic]
  id = "Et2"
  type = "socket"
  model = "virtio-net-pci"
  mac = "52:54:00:12:34:58"
  mcast = "230.0.0.1:3001"

[nic]
  id = "Et3"
  type = "socket"
  model = "virtio-net-pci"
  mac = "52:54:00:12:34:59"
  mcast = "230.0.0.1:3002"

[rtc]
  base = "localtime"
  clock = "vm"

[machine]
  type = "q35"
  accel = "kvm"
  mem-merge = "on"

[memory]
  size = "2G"

[smp-opts]
  cores = "1"
  threads = "1"
  sockets = "1"

[name]
  guest = "vEOS64"
